; Файл конфигурации плагина музыки
; Перечислить в кавычках через пробел на одной строке пару: "name" = "path"

[music_pack]
"music_pack" = 0

[request_songs_0]
"Antonk - Incomsystem Anthem" = "incom/greeting.mp3"
"Antonk - Пицца в обед" = "incom/greeting_lunch_pizza.mp3"
"Antonk - Код и Counter-Strike" = "incom/greeting_code_and_cs.mp3"
"Nikita - Меня зовут Антоха" = "incom/greeting_my_name_is_antoha.mp3"
"RomanPlan9 - Иди код пиши" = "incom/greeing_go_and_write_code.mp3"
"Antonk - Красные зайцы" = "incom/greeting_read_hears.mp3"
"IlnurT - Ты Гау" = "incom/greeting_you_gay.mp3"
"ICEGERGERT, SKY RAE - Гейследство" = "incom/greeting_icegergert_nasledstvo.mp3"
"Tom Petty - Love Is A Long Road" = "incom/greeting_love_is_a_long_road.mp3"
"The Weeknd - Popular" = "incom/greeting_popular_weekend.mp3"
"ivanzolo2004 - Баобаб" = "incom/greeting_baobab.mp3"
"Король и Шут - Лесник" = "incom/greeting_lesnik.mp3"
"Djo (Stranger things) - End of Beginning" = "incom/greeting_end_of_beginning.mp3"

[request_songs_1]
"Tonitaga - Инкомсистем и Новый год" = "incom/greeting_xmas_incomsystem_and_new_year.mp3"
"Tonitaga - Новогодняя" = "incom/greeting_xmas_incom.mp3"
"Tonitaga - Новогодний Код" = "incom/greeting_xmas_incom_new_year_code.mp3"
"Dean Martin - Let It Snow!" = "incom/greeting_xmas_let_it_snow.mp3"
"Brenda Lee - Rockin Around The Christmas Tree" = "incom/greeting_xmas_rocking_around.mp3"
"Wham! - Last Christmas" = "incom/greeting_xmas_last_christmas.mp3"
"Дискотека Авария - Новогодняя" = "incom/greeting_xmas_avaria_new_year.mp3"
"Верка Сердючка - Новогодняя" = "incom/greeting_xmas_verka_new_year.mp3"
"Андрей Губин - Зима холода" = "incom/greeting_xmas_zima_holoda.mp3"

[request_songs_255]
"Antonk - Incomsystem Anthem" = "incom/greeting.mp3"
"Antonk - Пицца в обед" = "incom/greeting_lunch_pizza.mp3"
"Antonk - Код и Counter-Strike" = "incom/greeting_code_and_cs.mp3"
"Nikita - Меня зовут Антоха" = "incom/greeting_my_name_is_antoha.mp3"
"RomanPlan9 - Иди код пиши" = "incom/greeing_go_and_write_code.mp3"
"Antonk - Красные зайцы" = "incom/greeting_read_hears.mp3"
"IlnurT - Ты Гау" = "incom/greeting_you_gay.mp3"
"ICEGERGERT, SKY RAE - Гейследство" = "incom/greeting_icegergert_nasledstvo.mp3"
"Tom Petty - Love Is A Long Road" = "incom/greeting_love_is_a_long_road.mp3"
"The Weeknd - Popular" = "incom/greeting_popular_weekend.mp3"
"ivanzolo2004 - Баобаб" = "incom/greeting_baobab.mp3"
"Король и Шут - Лесник" = "incom/greeting_lesnik.mp3"
"Djo (Stranger things) - End of Beginning" = "incom/greeting_end_of_beginning.mp3"
"Tonitaga - Инкомсистем и Новый год" = "incom/greeting_xmas_incomsystem_and_new_year.mp3"
"Tonitaga - Новогодняя" = "incom/greeting_xmas_incom.mp3"
"Tonitaga - Новогодний Код" = "incom/greeting_xmas_incom_new_year_code.mp3"
"Dean Martin - Let It Snow!" = "incom/greeting_xmas_let_it_snow.mp3"
"Brenda Lee - Rockin Around The Christmas Tree" = "incom/greeting_xmas_rocking_around.mp3"
"Wham! - Last Christmas" = "incom/greeting_xmas_last_christmas.mp3"
"Дискотека Авария - Новогодняя" = "incom/greeting_xmas_avaria_new_year.mp3"
"Верка Сердючка - Новогодняя" = "incom/greeting_xmas_verka_new_year.mp3"
"Андрей Губин - Зима холода" = "incom/greeting_xmas_zima_holoda.mp3"

[roundend_0]
"Roundend #1" = "incom/roundend1_v2.mp3"
"Roundend #2" = "incom/roundend2_v2.mp3"
"Roundend #3" = "incom/roundend3_v2.mp3"
"Roundend #4" = "incom/roundend4_v2.mp3"
"Roundend #5" = "incom/roundend5_v2.mp3"
"Roundend #6" = "incom/roundend6_v2.mp3"
"Roundend #7" = "incom/roundend7_v2.mp3"
"Roundend #8" = "incom/roundend8_v2.mp3"
"Roundend #9" = "incom/roundend9_v2.mp3"

[roundend_1]
"Roundend XMas #1" = "incom/roundend1_xmas_v2.mp3"
"Roundend XMas #2" = "incom/roundend2_xmas.mp3"
"Roundend XMas #3" = "incom/roundend3_xmas.mp3"
"Roundend XMas #4" = "incom/roundend4_xmas.mp3"
"Roundend XMas #5" = "incom/roundend5_xmas.mp3"
"Roundend XMas #6" = "incom/roundend6_xmas.mp3"
"Roundend XMas #7" = "incom/roundend7_xmas.mp3"
"Roundend XMas #8" = "incom/roundend8_xmas.mp3"

[roundend_255]
"Roundend #1" = "incom/roundend1_v2.mp3"
"Roundend #2" = "incom/roundend2_v2.mp3"
"Roundend #3" = "incom/roundend3_v2.mp3"
"Roundend #4" = "incom/roundend4_v2.mp3"
"Roundend #5" = "incom/roundend5_v2.mp3"
"Roundend #6" = "incom/roundend6_v2.mp3"
"Roundend #7" = "incom/roundend7_v2.mp3"
"Roundend #8" = "incom/roundend8_v2.mp3"
"Roundend #9" = "incom/roundend9_v2.mp3"
"Roundend XMas #1" = "incom/roundend1_xmas_v2.mp3"
"Roundend XMas #2" = "incom/roundend2_xmas.mp3"
"Roundend XMas #3" = "incom/roundend3_xmas.mp3"
"Roundend XMas #4" = "incom/roundend4_xmas.mp3"
"Roundend XMas #5" = "incom/roundend5_xmas.mp3"
"Roundend XMas #6" = "incom/roundend6_xmas.mp3"
"Roundend XMas #7" = "incom/roundend7_xmas.mp3"
"Roundend XMas #8" = "incom/roundend8_xmas.mp3